### ISSUE TITLE
YouTube каналы, miracl6 - Такого канала не существует.

### ISSUE THREAD

**Issue by activeprofi** [pymentor/python-roadmap#13]
[miracl6](https://www.youtube.com/channel/UCcrRKEJkKdhiYAuJ3cIYLZw)
Канал, где автор делится своим опытом в области образования, карьеры, саморазвития в области Data Science. А также уроки по Python и DS

**Такого канала не существует.**
![Screenshot_1](https://github.com/pymentor/python-roadmap/assets/2463964/a772ca04-a8d4-4a62-88db-0fefd7d3f3de)

**Comment by kosdmit** [comment]
У меня ссылка работает корректно. 
![image](https://github.com/user-attachments/assets/f5201e88-8961-4b16-8d2b-5f604a5a67d9)

Думаю Issue можно закрыть.
